//! # Aether Screenshot Capture
//!
//! Screen capture, region selection, and annotation for
//! the Aether compositor. Supports full-screen, active-window,
//! and free-form region capture with timer delay.
//!
//! Captured frames are stored as Prism objects with semantic
//! tags auto-generated by Synapse (e.g., "screenshot of terminal").

#![allow(dead_code)]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;

// ─── Capture Types ──────────────────────────────────────────────────────────

/// What to capture.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CaptureMode {
    /// Entire screen (all monitors)
    FullScreen,
    /// A single monitor
    Monitor(u32),
    /// Active/focused window
    ActiveWindow,
    /// User-selected rectangular region
    Region,
    /// User-drawn freeform path
    Freeform,
}

/// Image format for the captured frame.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImageFormat {
    /// PNG (lossless, default)
    Png,
    /// JPEG (lossy, smaller)
    Jpeg(u8), // quality 0-100
    /// BMP (uncompressed)
    Bmp,
    /// WebP
    WebP,
    /// Raw RGBA pixels
    RawRgba,
}

/// A rectangular region.
#[derive(Debug, Clone, Copy)]
pub struct Region {
    pub x: u32,
    pub y: u32,
    pub width: u32,
    pub height: u32,
}

impl Region {
    pub fn new(x: u32, y: u32, w: u32, h: u32) -> Self {
        Region { x, y, width: w, height: h }
    }

    pub fn area(&self) -> u64 {
        self.width as u64 * self.height as u64
    }

    /// Clamp to a screen boundary.
    pub fn clamp(&mut self, screen_w: u32, screen_h: u32) {
        if self.x + self.width > screen_w {
            self.width = screen_w.saturating_sub(self.x);
        }
        if self.y + self.height > screen_h {
            self.height = screen_h.saturating_sub(self.y);
        }
    }
}

// ─── Capture Options ────────────────────────────────────────────────────────

/// Options for a screenshot capture.
#[derive(Debug, Clone)]
pub struct CaptureOptions {
    /// What to capture
    pub mode: CaptureMode,
    /// Image format
    pub format: ImageFormat,
    /// Delay before capture (ms, 0 = immediate)
    pub delay_ms: u32,
    /// Include mouse cursor?
    pub include_cursor: bool,
    /// Include window shadow/decoration?
    pub include_decoration: bool,
    /// Auto-copy to clipboard?
    pub copy_to_clipboard: bool,
    /// Auto-save to Prism?
    pub save_to_prism: bool,
    /// Custom filename prefix
    pub filename_prefix: Option<String>,
}

impl Default for CaptureOptions {
    fn default() -> Self {
        CaptureOptions {
            mode: CaptureMode::FullScreen,
            format: ImageFormat::Png,
            delay_ms: 0,
            include_cursor: false,
            include_decoration: true,
            copy_to_clipboard: true,
            save_to_prism: true,
            filename_prefix: None,
        }
    }
}

// ─── Annotations ────────────────────────────────────────────────────────────

/// Annotation overlays.
#[derive(Debug, Clone)]
pub enum Annotation {
    /// Arrow pointing at (x, y)
    Arrow { from_x: f32, from_y: f32, to_x: f32, to_y: f32, color: u32 },
    /// Rectangle highlight
    Rectangle { region: Region, color: u32, thickness: u32 },
    /// Text label
    Text { x: f32, y: f32, text: String, color: u32, font_size: f32 },
    /// Blur/pixelate a region (for privacy)
    Blur { region: Region, strength: u32 },
    /// Highlight (semi-transparent overlay)
    Highlight { region: Region, color: u32, opacity: f32 },
    /// Numbered marker (for step-by-step guides)
    Marker { x: f32, y: f32, number: u32, color: u32 },
    /// Freehand drawing
    Freehand { points: Vec<(f32, f32)>, color: u32, thickness: f32 },
}

// ─── Captured Frame ─────────────────────────────────────────────────────────

/// A captured screenshot frame.
#[derive(Debug, Clone)]
pub struct CapturedFrame {
    /// Capture ID
    pub id: u64,
    /// Raw pixel data (RGBA)
    pub pixels: Vec<u8>,
    /// Width in pixels
    pub width: u32,
    /// Height in pixels
    pub height: u32,
    /// Capture region (relative to screen origin)
    pub region: Region,
    /// Image format used
    pub format: ImageFormat,
    /// Timestamp (ns)
    pub captured_at: u64,
    /// Annotations applied
    pub annotations: Vec<Annotation>,
    /// Prism OID (if saved)
    pub prism_oid: Option<[u8; 32]>,
    /// AI-generated description (from Synapse)
    pub description: Option<String>,
    /// encoded data (post-compression)
    pub encoded: Option<Vec<u8>>,
}

impl CapturedFrame {
    /// Raw data size in bytes (RGBA).
    pub fn raw_size(&self) -> u64 {
        self.width as u64 * self.height as u64 * 4
    }

    /// Encoded (compressed) size.
    pub fn encoded_size(&self) -> u64 {
        self.encoded.as_ref().map(|e| e.len() as u64).unwrap_or(self.raw_size())
    }
}

// ─── Screenshot Engine ──────────────────────────────────────────────────────

/// Screenshot statistics.
#[derive(Debug, Clone, Default)]
pub struct ScreenshotStats {
    pub captures_taken: u64,
    pub bytes_captured: u64,
    pub annotations_added: u64,
    pub saved_to_prism: u64,
    pub copied_to_clipboard: u64,
}

/// The Screenshot Engine.
pub struct ScreenshotEngine {
    /// Recent captures
    pub captures: Vec<CapturedFrame>,
    /// Max retained captures
    pub max_retained: usize,
    /// Next capture ID
    next_id: u64,
    /// Screen dimensions
    pub screen_width: u32,
    pub screen_height: u32,
    /// Statistics
    pub stats: ScreenshotStats,
}

impl ScreenshotEngine {
    pub fn new(screen_width: u32, screen_height: u32) -> Self {
        ScreenshotEngine {
            captures: Vec::new(),
            max_retained: 20,
            next_id: 1,
            screen_width,
            screen_height,
            stats: ScreenshotStats::default(),
        }
    }

    /// Capture a screenshot with the given options.
    pub fn capture(&mut self, options: &CaptureOptions, now: u64) -> u64 {
        let region = match options.mode {
            CaptureMode::FullScreen => {
                Region::new(0, 0, self.screen_width, self.screen_height)
            }
            CaptureMode::Monitor(_id) => {
                // In production: query compositor for monitor geometry
                Region::new(0, 0, self.screen_width, self.screen_height)
            }
            CaptureMode::ActiveWindow => {
                // In production: get focused window bounds from compositor
                Region::new(100, 100, 800, 600)
            }
            CaptureMode::Region | CaptureMode::Freeform => {
                // In production: show selection overlay, wait for user
                Region::new(0, 0, self.screen_width / 2, self.screen_height / 2)
            }
        };

        let pixel_count = region.area() as usize;
        // Create placeholder pixel data (in production: read from framebuffer)
        let pixels = alloc::vec![0u8; pixel_count * 4];

        let id = self.next_id;
        self.next_id += 1;

        let frame = CapturedFrame {
            id,
            pixels,
            width: region.width,
            height: region.height,
            region,
            format: options.format,
            captured_at: now,
            annotations: Vec::new(),
            prism_oid: None,
            description: None,
            encoded: None,
        };

        self.stats.captures_taken += 1;
        self.stats.bytes_captured += frame.raw_size();

        if options.copy_to_clipboard {
            self.stats.copied_to_clipboard += 1;
        }
        if options.save_to_prism {
            self.stats.saved_to_prism += 1;
        }

        self.captures.push(frame);

        // Prune old captures
        while self.captures.len() > self.max_retained {
            self.captures.remove(0);
        }

        id
    }

    /// Add an annotation to a capture.
    pub fn annotate(&mut self, capture_id: u64, annotation: Annotation) -> bool {
        if let Some(frame) = self.captures.iter_mut().find(|f| f.id == capture_id) {
            frame.annotations.push(annotation);
            self.stats.annotations_added += 1;
            true
        } else {
            false
        }
    }

    /// Set AI-generated description.
    pub fn set_description(&mut self, capture_id: u64, description: &str) {
        if let Some(frame) = self.captures.iter_mut().find(|f| f.id == capture_id) {
            frame.description = Some(String::from(description));
        }
    }

    /// Get a capture by ID.
    pub fn get(&self, capture_id: u64) -> Option<&CapturedFrame> {
        self.captures.iter().find(|f| f.id == capture_id)
    }

    /// Get the most recent capture.
    pub fn latest(&self) -> Option<&CapturedFrame> {
        self.captures.last()
    }

    /// List all captures (newest first).
    pub fn list(&self) -> Vec<(u64, u32, u32, u64)> {
        self.captures.iter().rev()
            .map(|f| (f.id, f.width, f.height, f.captured_at))
            .collect()
    }
}
