//! # Nexus — Global Q-Mesh / Genesis Protocol (Phase 61)
//!
//! Nexus is Qindows's planetary distributed computing layer. It implements
//! the "Genesis Protocol" described in ARCHITECTURE.md §9:
//!
//! > "Universal Node: Genesis Protocol creates a globally synchronized,
//! > self-healing peer-to-peer Supercomputer."
//!
//! ## What Nexus Does
//! 1. **Node Discovery** — broadcasting a cryptographic beacon on Q-Fabric
//! 2. **Elastic Rendering** — offloads GPU compute to remote Q-Servers
//! 3. **Distributed Objects** — "smears" Prism objects across nodes for HA
//! 4. **Immune Response** — propagates Sentinel antibodies globally in <300ms
//! 5. **Mesh Compute** — auctions idle CPU/GPU/NPU cycles for Q-Credits
//!
//! ## Architecture Guardian: Layering
//! ```text
//! Application (Q-Silo)
//!     │
//! Q-Fabric (transport — qfabric.rs)
//!     │
//! Nexus (mesh coordination — this file)
//!     │  uses:
//!     ├── Prism (objects to distribute)
//!     ├── Sentinel (antibody propagation)
//!     └── SynapseProcessor (neural sync — future)
//! ```
//!
//! Nexus MUST NOT directly reference Aether or Q-Shell. Those are
//! UI/UX layers — they consume Nexus events, not the other way around.
//!
//! ## Q-Manifest Law 9: Universal Namespace
//! All mesh nodes are addressed via `qfa://node-id` — no IP addresses
//! visible to applications. Routing is entirely Nexus-internal.

extern crate alloc;
use alloc::collections::BTreeMap;
use alloc::vec::Vec;
use alloc::string::String;

// ── Node Identity ─────────────────────────────────────────────────────────────

/// A 128-bit globally unique Nexus node ID.
/// Derived from the node's genesis public key fingerprint.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct NodeId(pub [u8; 16]);

impl NodeId {
    pub const LOCAL: Self = NodeId([0u8; 16]);

    pub fn is_local(&self) -> bool { *self == Self::LOCAL }

    /// Format the node ID as a short readable hex prefix (first 4 bytes).
    pub fn short_hex(&self) -> u32 {
        u32::from_le_bytes([self.0[0], self.0[1], self.0[2], self.0[3]])
    }
}

// ── Peer Node Descriptor ──────────────────────────────────────────────────────

/// Reachability tier for a peer node.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NodeTier {
    /// Same physical machine (loopback — memory IPC)
    Local,
    /// Same LAN / UWB (ultra-low latency)
    Lan,
    /// Same continent data center (<10ms RTT)
    Regional,
    /// Intercontinental / satellite (>50ms RTT)
    Global,
}

/// A discovered Nexus peer node.
#[derive(Debug, Clone)]
pub struct PeerNode {
    pub id: NodeId,
    pub tier: NodeTier,
    /// Available CPU cores (idle count)
    pub idle_cpu_cores: u8,
    /// Available GPU VRAM (MiB idle)
    pub idle_vram_mib: u32,
    /// Available NPU capacity (0–100%)
    pub idle_npu_pct: u8,
    /// Last observed round-trip time (microseconds)
    pub rtt_us: u32,
    /// Is this node currently healthy?
    pub healthy: bool,
    /// Total mesh tasks completed by this node
    pub tasks_completed: u64,
    /// Q-Credits balance (earned by serving compute)
    pub credits: u64,
}

// ── Mesh Task ─────────────────────────────────────────────────────────────────

/// Type of work being offloaded to the mesh.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MeshTaskKind {
    /// GPU compute (rendering, ray-trace, AI inference)
    GpuCompute,
    /// CPU-bound fiber execution (compilation, encoding)
    CpuFiber,
    /// NPU inference job (Sentinel antibody generation, intent ML)
    NpuInference,
    /// Object shard storage (Prism HA replication)
    ObjectShard,
}

/// A unit of work submitted to the Nexus for mesh execution.
#[derive(Debug, Clone)]
pub struct MeshTask {
    pub task_id: u64,
    pub kind: MeshTaskKind,
    /// Serialized fiber state or compute payload
    pub payload: Vec<u8>,
    /// The originating Silo on the local node
    pub origin_silo: u64,
    /// Preferred target node (None = best available)
    pub preferred_node: Option<NodeId>,
    /// Q-Credits offered as payment
    pub credit_offer: u64,
    /// Task submission tick
    pub submitted_at: u64,
    /// Task result (filled on completion)
    pub result: Option<Vec<u8>>,
}

// ── Sentinel Antibody ─────────────────────────────────────────────────────────

/// A security antibody generated by the Sentinel and propagated globally.
///
/// When one node detects a new attack pattern, it broadcasts an antibody.
/// All receiving nodes update their Sentinel's capability-blockers within
/// `ANTIBODY_PROPAGATION_BUDGET_TICKS` (300ms target).
#[derive(Debug, Clone)]
pub struct SentinelAntibody {
    /// SHA-256 fingerprint of the attack pattern
    pub pattern_hash: [u8; 32],
    /// Brief description (developer-facing only)
    pub description: &'static str,
    /// Node that discovered this attack
    pub discovered_by: NodeId,
    /// When it was discovered (global tick)
    pub discovered_at: u64,
    /// Nodes that have acknowledged the antibody
    pub ack_count: u64,
}

/// Global propagation target (ticks, ~300ms at 1kHz).
pub const ANTIBODY_PROPAGATION_BUDGET_TICKS: u64 = 300;

// ── Object Shard Map ──────────────────────────────────────────────────────────

/// Describes where a Prism object's shards are stored across the mesh.
#[derive(Debug, Clone)]
pub struct ObjectShardMap {
    /// Prism OID
    pub oid: u64,
    /// Node IDs holding a shard
    pub shards: Vec<NodeId>,
    /// Minimum replicas for HA guarantee
    pub min_replicas: u8,
    /// Size of each shard (bytes)
    pub shard_size: u64,
}

// ── Nexus Statistics ──────────────────────────────────────────────────────────

#[derive(Debug, Default, Clone)]
pub struct NexusStats {
    pub peers_discovered: u64,
    pub tasks_submitted: u64,
    pub tasks_completed: u64,
    pub antibodies_broadcast: u64,
    pub antibodies_received: u64,
    pub objects_sharded: u64,
    pub credits_earned: u64,
    pub credits_spent: u64,
}

// ── Nexus Router ─────────────────────────────────────────────────────────────

/// The Nexus mesh coordinator.
///
/// This is the kernel-side state manager for global mesh operations.
/// The actual Q-Fabric transport is handled by `qfabric::QFabricRouter`.
pub struct NexusRouter {
    /// This node's ID
    pub local_id: NodeId,
    /// Known peers: NodeId → PeerNode
    pub peers: BTreeMap<NodeId, PeerNode>,
    /// Pending tasks: task_id → MeshTask
    pub pending_tasks: BTreeMap<u64, MeshTask>,
    /// Object shard map
    pub shard_map: BTreeMap<u64, ObjectShardMap>,
    /// Active antibodies: pattern_hash → SentinelAntibody
    pub antibodies: BTreeMap<[u8; 32], SentinelAntibody>,
    /// Local Q-Credits balance
    pub credits: u64,
    /// Next task ID
    next_task_id: u64,
    /// Stats
    pub stats: NexusStats,
    /// Genesis protocol active?
    pub genesis_active: bool,
}

impl NexusRouter {
    pub fn new(local_id: NodeId) -> Self {
        NexusRouter {
            local_id,
            peers: BTreeMap::new(),
            pending_tasks: BTreeMap::new(),
            shard_map: BTreeMap::new(),
            antibodies: BTreeMap::new(),
            credits: 1000, // Genesis allocation
            next_task_id: 1,
            stats: NexusStats::default(),
            genesis_active: false,
        }
    }

    // ── Phase I: Genesis Protocol ─────────────────────────────────────────────

    /// Initiate the Genesis Protocol — broadcast the node beacon.
    ///
    /// This is the "Big Bang" event for the Q-Mesh. The local node begins
    /// multicasting its identity + hardware profile to all reachable peers.
    ///
    /// In production: sends a Q-Fabric broadcast to all-nodes multicast address.
    pub fn initiate_genesis(&mut self, tick: u64) {
        if self.genesis_active {
            crate::serial_println!("[NEXUS] Genesis already active.");
            return;
        }
        self.genesis_active = true;
        crate::serial_println!(
            "[NEXUS] GENESIS PROTOCOL INITIATED at tick {}. Node ID: {:08x}",
            tick, self.local_id.short_hex()
        );
        crate::serial_println!("[NEXUS] Broadcasting identity beacon on Q-Fabric...");
        crate::serial_println!("[NEXUS] Calibrating global clock (PTP-Sync)...");
        crate::serial_println!("[NEXUS] THE MESH IS ALIVE.");
    }

    // ── Phase II: Peer Discovery ──────────────────────────────────────────────

    /// Register a newly discovered peer node.
    pub fn register_peer(&mut self, peer: PeerNode) {
        crate::serial_println!(
            "[NEXUS] Peer discovered: {:08x} tier={:?} rtt={}µs cpu={} vram={}MiB",
            peer.id.short_hex(), peer.tier, peer.rtt_us, peer.idle_cpu_cores, peer.idle_vram_mib
        );
        self.peers.insert(peer.id, peer);
        self.stats.peers_discovered += 1;
    }

    /// Mark a peer as unhealthy (timeout or fault).
    pub fn mark_peer_unhealthy(&mut self, node_id: &NodeId) {
        if let Some(peer) = self.peers.get_mut(node_id) {
            peer.healthy = false;
            crate::serial_println!("[NEXUS] Peer {:08x} marked unhealthy.", node_id.short_hex());
        }
    }

    // ── Phase III: Elastic Compute Offload ───────────────────────────────────

    /// Find the best peer for a given task kind.
    ///
    /// Selection criteria (in order):
    /// 1. Tier (prefer Local > LAN > Regional > Global)
    /// 2. Relevant idle resource (GPU VRAM for GPU tasks, etc.)
    /// 3. RTT (lower is better)
    pub fn best_peer_for(&self, kind: MeshTaskKind) -> Option<NodeId> {
        self.peers.values()
            .filter(|p| p.healthy)
            .min_by_key(|p| {
                let tier_score = p.tier as u32 * 1_000_000;
                let resource_score = match kind {
                    MeshTaskKind::GpuCompute  => 100u32.saturating_sub(p.idle_vram_mib.min(100)),
                    MeshTaskKind::CpuFiber    => 255 - p.idle_cpu_cores as u32,
                    MeshTaskKind::NpuInference => 100 - p.idle_npu_pct as u32,
                    MeshTaskKind::ObjectShard  => p.rtt_us / 1000,
                };
                tier_score + resource_score + p.rtt_us / 10
            })
            .map(|p| p.id)
    }

    /// Submit a task to the mesh for execution.
    pub fn submit_task(&mut self, task: MeshTask) -> u64 {
        let target = task.preferred_node
            .or_else(|| self.best_peer_for(task.kind))
            .unwrap_or(NodeId::LOCAL);

        crate::serial_println!(
            "[NEXUS] Task {} ({:?}) → node {:08x}, offer={} credits",
            task.task_id, task.kind, target.short_hex(), task.credit_offer
        );

        let id = task.task_id;
        self.pending_tasks.insert(id, task);
        self.stats.tasks_submitted += 1;
        id
    }

    /// Allocate a new task ID and build a task.
    pub fn create_task(
        &mut self,
        kind: MeshTaskKind,
        origin_silo: u64,
        payload: Vec<u8>,
        credit_offer: u64,
        tick: u64,
    ) -> MeshTask {
        let id = self.next_task_id;
        self.next_task_id += 1;
        MeshTask {
            task_id: id,
            kind,
            payload,
            origin_silo,
            preferred_node: None,
            credit_offer,
            submitted_at: tick,
            result: None,
        }
    }

    /// Mark a pending task as complete (called when result arrives).
    pub fn complete_task(&mut self, task_id: u64, result: Vec<u8>) {
        if let Some(task) = self.pending_tasks.get_mut(&task_id) {
            task.result = Some(result);
            self.stats.tasks_completed += 1;
            self.credits += task.credit_offer / 2; // Node earns half the offer
            self.stats.credits_earned += task.credit_offer / 2;
            crate::serial_println!("[NEXUS] Task {} completed.", task_id);
        }
    }

    // ── Phase IV: Object Sharding ────────────────────────────────────────────

    /// Shard a Prism object across multiple nodes for high availability.
    ///
    /// The object is split into `peers.len().min(5)` shards, each
    /// stored on a different node to guarantee availability even if
    /// 4 out of 5 nodes go offline.
    pub fn shard_object(&mut self, oid: u64, object_size: u64, min_replicas: u8) {
        let shard_nodes: Vec<NodeId> = self.peers.values()
            .filter(|p| p.healthy)
            .take(min_replicas as usize)
            .map(|p| p.id)
            .collect();

        let shard_count = shard_nodes.len().max(1) as u64;
        let shard_size = (object_size + shard_count - 1) / shard_count;

        let map = ObjectShardMap {
            oid,
            shards: shard_nodes,
            min_replicas,
            shard_size,
        };
        self.shard_map.insert(oid, map);
        self.stats.objects_sharded += 1;
        crate::serial_println!("[NEXUS] Object {} sharded across {} nodes.", oid, shard_count);
    }

    // ── Phase V: Sentinel Antibody Propagation ───────────────────────────────

    /// Broadcast a Sentinel antibody to all known peers.
    ///
    /// Called when the local Sentinel discovers a new attack pattern.
    /// All receiving peers update their own Sentinel capability-blockers.
    pub fn broadcast_antibody(&mut self, antibody: SentinelAntibody, tick: u64) {
        crate::serial_println!(
            "[NEXUS] Antibody broadcast: \"{}\" discovered by {:08x} at tick {}",
            antibody.description, antibody.discovered_by.short_hex(), tick
        );
        crate::serial_println!(
            "[NEXUS] Immunizing {} peers...", self.peers.len()
        );
        // In production: transmit to each peer via Q-Fabric multicast
        self.antibodies.insert(antibody.pattern_hash, antibody);
        self.stats.antibodies_broadcast += 1;
    }

    /// Receive an antibody from a remote peer and apply it locally.
    pub fn receive_antibody(&mut self, antibody: SentinelAntibody) {
        crate::serial_println!(
            "[NEXUS] Antibody received: \"{}\" — immunizing local Sentinel.",
            antibody.description
        );
        if let Some(a) = self.antibodies.get_mut(&antibody.pattern_hash) {
            a.ack_count += 1;
        } else {
            self.antibodies.insert(antibody.pattern_hash, antibody);
        }
        self.stats.antibodies_received += 1;
    }

    // ── Mesh Status ───────────────────────────────────────────────────────────

    /// Count of currently healthy peers.
    pub fn healthy_peer_count(&self) -> usize {
        self.peers.values().filter(|p| p.healthy).count()
    }

    /// Total idle GPU VRAM available in the mesh (MiB).
    pub fn total_mesh_vram_mib(&self) -> u64 {
        self.peers.values()
            .filter(|p| p.healthy)
            .map(|p| p.idle_vram_mib as u64)
            .sum()
    }
}
