//! # Q-Update — Atomic Hot-Swap System Updater (Phase 70)
//!
//! Q-Update implements live OS and package updates with **zero reboot**.
//!
//! ## ARCHITECTURE.md §System Benchmarks
//! > "System Update: Windows requires full reboot | Qindows: Atomic hot-swap, zero reboot"
//!
//! ## Architecture Guardian: How hot-swap works with existing modules
//! ```text
//! Nexus (nexus.rs)        ← downloads update package over Q-Mesh
//!     │  UpdatePackage
//!     ▼
//! Q-Update (this module)  ← validates, stages, and applies atomically
//!     │  UpdateCommit
//!     ▼
//! QFS Ghost-Write (qfs_ghost.rs) ← commits as CoW atomic pointer swap
//!     │  new OID
//!     ▼
//! Hotswap (hotswap.rs)    ← live-patches running code pages
//! ```
//!
//! ## Law 2: Immutable Binaries
//! Updates never OVERWRITE existing binaries. A new content-addressed object
//! is staged, validated, and only then the Prism pointer is atomically moved.
//! Old version becomes a Shadow Object — rollback is instant.
//!
//! ## Law 10: Graceful Degradation
//! If an update fails mid-apply, the pointer was never moved.
//! The system is always in a valid state. No partial-update corruption possible.

extern crate alloc;
use alloc::collections::BTreeMap;
use alloc::string::String;
use alloc::vec::Vec;
use alloc::string::ToString;

// ── Update Package ────────────────────────────────────────────────────────────

/// Type of thing being updated.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UpdateTarget {
    /// The Qernel binary (live kernel hot-patch)
    Qernel,
    /// A user-space application (Q-Ledger entry swap)
    Application,
    /// A shared library (single dedup object → all apps updated instantly)
    SharedLibrary,
    /// Security microcode / firmware (requires next-boot application)
    Firmware,
    /// ARCHITECTURE.md or system documentation
    Documentation,
}

/// A signed, content-addressed update package.
#[derive(Debug, Clone)]
pub struct UpdatePackage {
    /// Unique update ID (autogenerated by Nexus on download)
    pub update_id: u64,
    /// What is being updated
    pub target: UpdateTarget,
    /// For Application/SharedLibrary: the Q-Ledger app/library ID
    pub target_id: String,
    /// Semantic version being upgraded FROM
    pub from_version: String,
    /// Semantic version being upgraded TO
    pub to_version: String,
    /// Content hash of the new binary
    pub new_hash: [u8; 32],
    /// Content hash of the OLD binary (ensures we're upgrading the right version)
    pub old_hash: [u8; 32],
    /// Publisher Ed25519 signature over (update_id ‖ target_id ‖ new_hash)
    pub signature: [u8; 64],
    /// Size of the new binary (bytes)
    pub payload_bytes: u64,
    /// Is this a security-critical update?
    pub is_security_critical: bool,
    /// Human-readable changelog
    pub changelog: String,
}

/// Current phase of an update operation.  
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UpdatePhase {
    /// Queued, not yet started
    Queued,
    /// Downloading payload from Nexus mesh
    Downloading { pct: u8 },
    /// Verifying signature and hash
    Verifying,
    /// Staged in Prism (new OID written, but pointer not yet moved)
    Staged,
    /// Atomically applying (pointer swap + optional hotswap live-patch)
    Applying,
    /// Successfully applied
    Applied,
    /// Rolled back (old pointer restored)
    RolledBack,
    /// Failed unrecoverably (should not happen due to Law 10)
    Failed,
}

/// Result of applying an update.
#[derive(Debug, Clone)]
pub struct UpdateResult {
    pub update_id: u64,
    pub phase: UpdatePhase,
    /// New Prism OID for the updated object (None on failure)
    pub new_prism_oid: Option<u64>,
    /// Old Prism OID preserved as Shadow Object for instant rollback
    pub shadow_oid: Option<u64>,
    /// Elapsed ticks for the whole operation
    pub elapsed_ticks: u64,
    /// Was a live hot-patch applied (for Qernel updates)?
    pub hotpatched: bool,
}

// ── Update Queue ──────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct UpdateRecord {
    pub package: UpdatePackage,
    pub phase: UpdatePhase,
    pub queued_at: u64,
    pub started_at: Option<u64>,
    pub result: Option<UpdateResult>,
}

// ── Q-Update Statistics ───────────────────────────────────────────────────────

#[derive(Debug, Default, Clone)]
pub struct UpdateStats {
    pub packages_queued: u64,
    pub packages_applied: u64,
    pub packages_rolled_back: u64,
    pub packages_failed: u64,
    pub security_updates_applied: u64,
    pub total_bytes_updated: u64,
}

// ── Q-Update Engine ───────────────────────────────────────────────────────────

/// The Q-Update kernel engine.
pub struct QUpdateEngine {
    /// Pending/active update records: update_id → record
    pub queue: BTreeMap<u64, UpdateRecord>,
    /// Completed update history (last N updates)
    pub history: Vec<UpdateResult>,
    /// Maximum history entries to retain
    pub max_history: usize,
    /// Stats
    pub stats: UpdateStats,
    /// Next synthetic update ID (in production: provided by Nexus)
    next_id: u64,
}

impl QUpdateEngine {
    pub fn new() -> Self {
        QUpdateEngine {
            queue: BTreeMap::new(),
            history: Vec::new(),
            max_history: 64,
            stats: UpdateStats::default(),
            next_id: 1,
        }
    }

    /// Queue a new update package for application.
    pub fn queue_update(&mut self, package: UpdatePackage, tick: u64) -> u64 {
        let id = package.update_id;
        crate::serial_println!(
            "[UPDATE] Queued: {} v{} → v{} ({}B, security={})",
            package.target_id, package.from_version, package.to_version,
            package.payload_bytes, package.is_security_critical
        );
        self.queue.insert(id, UpdateRecord {
            package,
            phase: UpdatePhase::Queued,
            queued_at: tick,
            started_at: None,
            result: None,
        });
        self.stats.packages_queued += 1;
        id
    }

    /// Verify a package's signature and content hash.
    ///
    /// In production: Ed25519 verify over TPM. Here we check the hash round-trip.
    fn verify_package(pkg: &UpdatePackage) -> bool {
        // Production: ed25519_verify(pkg.publisher_key, msg, pkg.signature)
        // Placeholder: accept if new_hash ≠ old_hash (version change)
        pkg.new_hash != pkg.old_hash
    }

    /// Apply the next queued update atomically (Law 2, Law 10).
    ///
    /// Called by the kernel update scheduler fiber.
    pub fn apply_next(&mut self, tick: u64) -> Option<UpdateResult> {
        // Find first queued entry
        let update_id = self.queue.values()
            .find(|r| r.phase == UpdatePhase::Queued)
            .map(|r| r.package.update_id)?;

        let record = self.queue.get_mut(&update_id)?;
        record.started_at = Some(tick);

        // Phase: Verifying
        record.phase = UpdatePhase::Verifying;
        crate::serial_println!("[UPDATE] Verifying package {}...", update_id);

        if !Self::verify_package(&record.package) {
            record.phase = UpdatePhase::Failed;
            crate::serial_println!("[UPDATE] Package {} FAILED verification.", update_id);
            self.stats.packages_failed += 1;
            let result = UpdateResult {
                update_id,
                phase: UpdatePhase::Failed,
                new_prism_oid: None,
                shadow_oid: None,
                elapsed_ticks: tick.saturating_sub(record.queued_at),
                hotpatched: false,
            };
            record.result = Some(result.clone());
            return Some(result);
        }

        // Phase: Staged — CoW write via QFS Ghost-Write (simulated here)
        record.phase = UpdatePhase::Staged;
        let new_oid = 0x0EA0_0000_0000_0000 | (update_id & 0xFFFF_FFFF);
        let shadow_oid = 0x5EED_0000_0000_0000 | (update_id & 0xFFFF_FFFF);
        crate::serial_println!(
            "[UPDATE] Package {} staged: new_OID={:016x} shadow_OID={:016x}",
            update_id, new_oid, shadow_oid
        );

        // Phase: Applying — atomic pointer swap
        record.phase = UpdatePhase::Applying;
        let is_qernel = record.package.target == UpdateTarget::Qernel;
        crate::serial_println!(
            "[UPDATE] Package {} APPLYING (hotpatch={})...", update_id, is_qernel
        );

        // Phase: Applied
        record.phase = UpdatePhase::Applied;
        crate::serial_println!(
            "[UPDATE] Package {} APPLIED — {} v{} live. Zero reboot.",
            update_id, record.package.target_id, record.package.to_version
        );
        crate::serial_println!(
            "[UPDATE] Rollback available: shadow_OID={:016x}", shadow_oid
        );

        self.stats.packages_applied += 1;
        self.stats.total_bytes_updated += record.package.payload_bytes;
        if record.package.is_security_critical {
            self.stats.security_updates_applied += 1;
        }

        let elapsed = tick.saturating_sub(record.queued_at);
        let result = UpdateResult {
            update_id,
            phase: UpdatePhase::Applied,
            new_prism_oid: Some(new_oid),
            shadow_oid: Some(shadow_oid),
            elapsed_ticks: elapsed,
            hotpatched: is_qernel,
        };
        record.result = Some(result.clone());

        // Move to history
        if self.history.len() >= self.max_history {
            self.history.remove(0);
        }
        self.history.push(result.clone());
        self.queue.remove(&update_id);

        Some(result)
    }

    /// Rollback the most recently applied update (instant — shadow pointer swap).
    pub fn rollback_last(&mut self, tick: u64) -> bool {
        let last = match self.history.last_mut() {
            Some(r) if r.phase == UpdatePhase::Applied => r,
            _ => {
                crate::serial_println!("[UPDATE] No applied update to rollback.");
                return false;
            }
        };
        if let Some(shadow) = last.shadow_oid {
            crate::serial_println!(
                "[UPDATE] ROLLING BACK update {} — restoring shadow_OID={:016x}",
                last.update_id, shadow
            );
            last.phase = UpdatePhase::RolledBack;
            self.stats.packages_rolled_back += 1;
            true
        } else {
            false
        }
    }
}
