//! # Prism — Semantic Object Storage
//!
//! Qindows replaces hierarchical file systems and the Registry with
//! the Prism Object Graph. Every file, email, and message is a
//! Semantic Object in a multi-dimensional graph — found by meaning.
//!
//! Key properties:
//! - **Content-Addressable**: Data stored by cryptographic hash (O-ID)
//! - **Immutable & Versioned**: Changes create Shadow Objects
//! - **Globally Deduplicated**: One copy, many views
//! - **Semantic Search**: "Show me the contract from Sarah" works

#![no_std]
#![allow(dead_code)]

extern crate alloc;

pub mod math_ext;

pub mod block;
pub mod btree;
pub mod btree_iter;
pub mod blob;
pub mod bloom;
pub mod compression;
pub mod dedup;
pub mod encryption;
pub mod extents;
pub mod fsck;
pub mod journal;
pub mod key_rotation;
pub mod mvcc;
pub mod quota;
pub mod snapshot;
pub mod vfs;
pub mod tiering;
pub mod search_index;
pub mod crash_recovery;
pub mod gc;
pub mod migration;
pub mod qstream;
pub mod qegistry;
pub mod shadow_sync;
pub mod infinite_drive;
pub mod qaudit;
pub mod qlock;
pub mod qshare;
pub mod qtrash;
pub mod qsymlink;
pub mod qacl;
pub mod qattr;
pub mod qlink;
pub mod qnotify_store;
pub mod qpipe;
pub mod qwatch;
pub mod qstat;
pub mod qcache;

use alloc::string::String;
use alloc::vec::Vec;

/// Object ID — a 256-bit cryptographic hash of the object's content.
pub type OID = [u8; 32];

/// Q-Node: 4KB metadata block, always kept in CPU L3 cache.
///
/// This is the fundamental unit of storage in Qindows.
/// Files, apps, settings — everything is a Q-Node.
#[derive(Debug, Clone)]
pub struct QNode {
    /// Unique content-based identifier
    pub oid: OID,
    /// Object-specific encryption key
    pub entropy_key: [u8; 32],
    /// AI-computed similarity vector for semantic search
    pub vector_hash: [f32; 3],
    /// Parent version pointer (lineage chain)
    pub lineage: Option<OID>,
    /// Object metadata
    pub metadata: ObjectMetadata,
    /// Chunk hashes from the Deduplication Engine
    pub chunks: Vec<crate::dedup::ChunkHash>,
}

/// Metadata associated with a Q-Node.
#[derive(Debug, Clone)]
pub struct ObjectMetadata {
    /// Human-readable label (not a filesystem "name")
    pub label: String,
    /// Semantic tags (auto-generated by NPU)
    pub tags: Vec<String>,
    /// Creation timestamp (scheduler ticks since boot)
    pub created_at: u64,
    /// Last access timestamp
    pub accessed_at: u64,
    /// Size of the object data in bytes
    pub size_bytes: u64,
    /// MIME-like content type
    pub content_type: String,
    /// Silo ID of the creator
    pub creator_silo: u64,
}

pub struct PrismGraph {
    /// All objects in the local graph
    objects: Vec<QNode>,
    /// Global Chunk Index
    pub dedup: crate::dedup::DedupEngine,
    /// Write-Ahead Journal for crash recovery
    pub journal: crate::journal::Journal,
}

impl PrismGraph {
    pub fn new() -> Self {
        PrismGraph {
            objects: Vec::new(),
            dedup: crate::dedup::DedupEngine::new(),
            journal: crate::journal::Journal::new(),
        }
    }

    /// Store a new object in the graph.
    ///
    /// If an object with the same OID already exists (deduplication),
    /// the existing one is returned instead.
    pub fn store(&mut self, mut node: QNode, data: &[u8]) -> &QNode {
        if let Some(pos) = self.objects.iter().position(|n| n.oid == node.oid) {
            return &self.objects[pos];
        }

        // WAL Step 1: Record intent in journal BEFORE writing
        let oid_copy = node.oid;
        let entry = self.journal.begin(crate::journal::JournalOp::Insert, oid_copy);
        entry.data_length = data.len() as u64;
        let seq = entry.seq;

        // WAL Step 2: Perform the actual write (chunk + insert)
        let chunk_hashes = self.dedup.store_object(data);
        node.chunks = chunk_hashes;
        self.objects.push(node);

        // WAL Step 3: Commit the journal entry — write is now durable
        self.journal.commit(seq);

        self.objects.last().unwrap()
    }

    /// Resolve an intent query — the "Hello World" of Prism.
    ///
    /// Fix #13: implements character-bigram TF cosine similarity against
    /// label + tags for semantic matching.
    ///
    /// Algorithm:
    /// - Decompose the query into character bigrams
    /// - For each QNode, count bigram matches in label + tags (= TF score)
    /// - Rank by score descending (then by accessed_at as a tie-breaker)
    /// - In production: replace with NPU vector embedding + ANN search
    pub fn resolve_intent(&self, query: &str, limit: usize) -> Vec<&QNode> {
        // Build query bigram set (character pairs, case-insensitive)
        let q_lower: alloc::string::String = query.chars()
            .flat_map(|c| c.to_lowercase())
            .collect();
        let q_bytes = q_lower.as_bytes();

        let bigram_score = |text: &str| -> u32 {
            if q_bytes.len() < 2 {
                // Single char: simple contains check
                let t_lower: alloc::string::String = text.chars()
                    .flat_map(|c| c.to_lowercase()).collect();
                return if t_lower.as_bytes().windows(1).any(|w| w == &q_bytes[..1]) { 1 } else { 0 };
            }
            let t_lower: alloc::string::String = text.chars()
                .flat_map(|c| c.to_lowercase()).collect();
            let t_bytes = t_lower.as_bytes();

            // Count how many query bigrams are present in the target text
            let mut matches = 0u32;
            for qb in q_bytes.windows(2) {
                if t_bytes.windows(2).any(|tb| tb == qb) {
                    matches += 1;
                }
            }
            matches
        };

        // Score each node against query
        let mut scored: alloc::vec::Vec<(u32, u64, &QNode)> = self.objects.iter()
            .map(|node| {
                let mut score = bigram_score(&node.metadata.label);
                for tag in &node.metadata.tags {
                    score += bigram_score(tag.as_str());
                }
                (score, node.metadata.accessed_at, node)
            })
            .collect();

        // Sort: highest score first, then most-recently-accessed as tie-breaker
        scored.sort_by(|a, b| b.0.cmp(&a.0).then(b.1.cmp(&a.1)));

        // Return up to `limit` results
        scored.into_iter()
            .filter(|(score, _, _)| *score > 0 || query.is_empty())
            .take(limit)
            .map(|(_, _, node)| node)
            .collect()
    }

    /// Get an object by its exact OID.
    pub fn get(&self, oid: &OID) -> Option<&QNode> {
        self.objects.iter().find(|n| &n.oid == oid)
    }

    /// Get the version history (lineage chain) of an object.
    pub fn get_lineage(&self, oid: &OID) -> Vec<&QNode> {
        let mut chain = Vec::new();
        let mut current = self.get(oid);
        while let Some(node) = current {
            chain.push(node);
            current = node.lineage.as_ref().and_then(|parent| self.get(parent));
        }
        chain
    }

    /// Return the total number of stored objects in the graph.
    ///
    /// Used by Q-Shell `prism stats` to display a live count.
    pub fn object_count(&self) -> usize {
        self.objects.len()
    }
}

/// Ghost-Write: create a new version of an object.
///
/// The old version becomes a Shadow Object (still accessible
/// for instant rollback). No data is ever truly deleted.
pub fn ghost_write(graph: &mut PrismGraph, parent_oid: &OID, new_node: QNode, data: &[u8]) -> OID {
    let oid = new_node.oid;
    let mut versioned = new_node;
    versioned.lineage = Some(*parent_oid);

    // WAL: Journal the Update operation before storing
    let entry = graph.journal.begin(crate::journal::JournalOp::Update, oid);
    entry.data_length = data.len() as u64;
    // Record parent pointer for undo
    entry.prev_offset = 0;
    entry.prev_length = 32; // OID size
    let seq = entry.seq;

    // Dedup + store
    let chunk_hashes = graph.dedup.store_object(data);
    versioned.chunks = chunk_hashes;

    // Push without calling store() to avoid double-journaling
    if graph.objects.iter().all(|n| n.oid != versioned.oid) {
        graph.objects.push(versioned);
    }

    // Commit the journal entry
    graph.journal.commit(seq);
    oid
}
