//! # Prism — Semantic Object Storage
//!
//! Qindows replaces hierarchical file systems and the Registry with
//! the Prism Object Graph. Every file, email, and message is a
//! Semantic Object in a multi-dimensional graph — found by meaning.
//!
//! Key properties:
//! - **Content-Addressable**: Data stored by cryptographic hash (O-ID)
//! - **Immutable & Versioned**: Changes create Shadow Objects
//! - **Globally Deduplicated**: One copy, many views
//! - **Semantic Search**: "Show me the contract from Sarah" works

#![no_std]

extern crate alloc;

pub mod block;
pub mod btree;
pub mod btree_iter;
pub mod blob;
pub mod bloom;
pub mod changelog;
pub mod compression;
pub mod dedup;
pub mod encryption;
pub mod extents;
pub mod fsck;
pub mod journal;
pub mod key_rotation;
pub mod mvcc;
pub mod quota;
pub mod snapshot;
pub mod vfs;
pub mod wal;
pub mod tiering;
pub mod search_index;
pub mod crash_recovery;
pub mod gc;
pub mod migration;
pub mod qstream;
pub mod qegistry;
pub mod shadow_sync;
pub mod infinite_drive;
pub mod qaudit;
pub mod qsearch;
pub mod qlock;
pub mod qversions;
pub mod qshare;
pub mod qtrash;
pub mod qcompress;
pub mod qencrypt;
pub mod qsymlink;

use alloc::string::String;
use alloc::vec::Vec;

/// Object ID — a 256-bit cryptographic hash of the object's content.
pub type OID = [u8; 32];

/// Q-Node: 4KB metadata block, always kept in CPU L3 cache.
///
/// This is the fundamental unit of storage in Qindows.
/// Files, apps, settings — everything is a Q-Node.
#[derive(Debug, Clone)]
pub struct QNode {
    /// Unique content-based identifier
    pub oid: OID,
    /// Object-specific encryption key
    pub entropy_key: [u8; 32],
    /// AI-computed similarity vector for semantic search
    pub vector_hash: [f32; 3],
    /// Parent version pointer (lineage chain)
    pub lineage: Option<OID>,
    /// Object metadata
    pub metadata: ObjectMetadata,
}

/// Metadata associated with a Q-Node.
#[derive(Debug, Clone)]
pub struct ObjectMetadata {
    /// Human-readable label (not a filesystem "name")
    pub label: String,
    /// Semantic tags (auto-generated by NPU)
    pub tags: Vec<String>,
    /// Creation timestamp (scheduler ticks since boot)
    pub created_at: u64,
    /// Last access timestamp
    pub accessed_at: u64,
    /// Size of the object data in bytes
    pub size_bytes: u64,
    /// MIME-like content type
    pub content_type: String,
    /// Silo ID of the creator
    pub creator_silo: u64,
}

/// The Prism Object Graph — the central storage engine.
pub struct PrismGraph {
    /// All objects in the local graph
    objects: Vec<QNode>,
}

impl PrismGraph {
    pub const fn new() -> Self {
        PrismGraph {
            objects: Vec::new(),
        }
    }

    /// Store a new object in the graph.
    ///
    /// If an object with the same OID already exists (deduplication),
    /// the existing one is returned instead.
    pub fn store(&mut self, node: QNode) -> &QNode {
        if let Some(existing) = self.objects.iter().find(|n| n.oid == node.oid) {
            return existing;
        }
        self.objects.push(node);
        self.objects.last().unwrap()
    }

    /// Resolve an intent query — the "Hello World" of Prism.
    ///
    /// This is a semantic search: it doesn't match filenames,
    /// it matches meaning using the vector_hash field.
    pub fn resolve_intent(&self, _query: &str, limit: usize) -> Vec<&QNode> {
        // In production: use NPU to compute query embedding,
        // then find nearest vectors via cosine similarity.
        // For now, return the most recently accessed objects.
        let mut results: Vec<&QNode> = self.objects.iter().collect();
        results.sort_by(|a, b| b.metadata.accessed_at.cmp(&a.metadata.accessed_at));
        results.truncate(limit);
        results
    }

    /// Get an object by its exact OID.
    pub fn get(&self, oid: &OID) -> Option<&QNode> {
        self.objects.iter().find(|n| &n.oid == oid)
    }

    /// Get the version history (lineage chain) of an object.
    pub fn get_lineage(&self, oid: &OID) -> Vec<&QNode> {
        let mut chain = Vec::new();
        let mut current = self.get(oid);
        while let Some(node) = current {
            chain.push(node);
            current = node.lineage.as_ref().and_then(|parent| self.get(parent));
        }
        chain
    }
}

/// Ghost-Write: create a new version of an object.
///
/// The old version becomes a Shadow Object (still accessible
/// for instant rollback). No data is ever truly deleted.
pub fn ghost_write(graph: &mut PrismGraph, parent_oid: &OID, new_node: QNode) -> OID {
    let oid = new_node.oid;
    let mut versioned = new_node;
    versioned.lineage = Some(*parent_oid);
    graph.store(versioned);
    oid
}
